To create an array, seperate the elements with a comma or space.

In [58]:
A = [1 2 3 4]

1×4 Array{Int64,2}:
 1  2  3  4

This constructs a two dimensional array with 1 row.
Here are two ways to construct a matrix

In [59]:
A = [1 2 3; 4 5 6; 7 8 9]
A = [1 2 3
4 5 6
7 8 10]

3×3 Array{Int64,2}:
 1  2   3
 4  5   6
 7  8  10

We can also construct arrays using functions. For example, to create a length 5 vector of zeros.

In [60]:
z = zeros(5)

5-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0

Note that in Matlab the zeros(5) command gives you a 5x5 matrix. Matlab has no concept of 1 dimensional arrays.

To perform operations on matrices, we want to use dot notation described below. This is a unique and very powerful feature of Julia. In Julia, functions are generally written exclusively for scalar arguments unless there is a well defined matrix version. For example, element-wise multiplication and matrix multiplication are not the same thing, nor is element-wise exponential and matrix exponential.

The following is an error for arrays. (there is no base 10 matrix logorithim)

In [61]:
@show log10(2.)
@show log10(A)

log10(2.0) = 0.3010299956639812


LoadError: MethodError: no method matching log10(::Array{Int64,2})
Closest candidates are:
  log10(!Matched::BigFloat) at mpfr.jl:611
  log10(!Matched::Missing) at math.jl:1056
  log10(!Matched::Complex{Float16}) at math.jl:1005
  ...

To apply this element-wise, use a dot

In [62]:
log10.(A)

3×3 Array{Float64,2}:
 0.0       0.30103  0.477121
 0.60206   0.69897  0.778151
 0.845098  0.90309  1.0     

This dot notation automatically converts the above into a loop which calls the function on scalars.

In [63]:
out = zeros(size(A))
for i in eachindex(A)
    out[i] = log10(A[i])
end
out

3×3 Array{Float64,2}:
 0.0       0.30103  0.477121
 0.60206   0.69897  0.778151
 0.845098  0.90309  1.0     

This notation generalizes to a whole line of computations. This is called fusing.

In [64]:
@show exp.(A) .+ sin.(A) .^ A
## Equivalent to 
out = zeros(size(A))
for i in eachindex(A)
    a = A[i]
    out[i] = exp(a) + sin(a)^a
end
@show out;

exp.(A) .+ sin.(A) .^ A = [3.55975 8.21588 20.0883; 54.9262 147.602 403.429; 1096.69 2981.88 22026.5]
out = [3.55975 8.21588 20.0883; 54.9262 147.602 403.429; 1096.69 2981.88 22026.5]


Usual matrix operations work mostly as in Matlab

In [65]:
@show A'
@show A*A 
@show A * inv(A);

A' = [1 4 7; 2 5 8; 3 6 10]
A * A = [30 36 45; 66 81 102; 109 134 169]
A * inv(A) = [1.0 0.0 0.0; -8.88178e-16 1.0 -8.88178e-16; 0.0 0.0 1.0]


However, the comma means something different here. To join two arrays horizontally, only the space is acceptable. A comma will give you an array of arrays.

In [66]:
[A A]

3×6 Array{Int64,2}:
 1  2   3  1  2   3
 4  5   6  4  5   6
 7  8  10  7  8  10

In [67]:
[A, A]

2-element Array{Array{Int64,2},1}:
 [1 2 3; 4 5 6; 7 8 10]
 [1 2 3; 4 5 6; 7 8 10]

In [68]:
[A;A]

6×3 Array{Int64,2}:
 1  2   3
 4  5   6
 7  8  10
 1  2   3
 4  5   6
 7  8  10